#### REQUIRED VALUES ####

## What is the name of the job? Results will be stored in `results_dir/job_prefix/`
results_dir: "results"    # This can also be an absolute path
job_prefix: "test"

# Parent directory for the input data, which can be genomes or antismash folders
data_dir: "example"

## File extension to be used
# Use `gbff`, `gbk`, `fna`, etc for genomes that will be run through antismash
# Leave blank for existing antismash results
data_ext: gbff

# For fasta files, GFF3 gene features can be provided separately. Files must
#   have the same basename, ex: `A01.fa` and `A01.gff`.
gff3_ext: null  # gff
# TODO: NOT IMPLEMENTED

## antiSMASH configuration
# Until antiSMASH 7 is conda installable, you'll have to provide your own
#   installation.
antismash_command: "antismash" # or maybe `python /path/to/run_antismash.py`
antismash_conda: "antismash7"
antismash_flags: "--genefinding-tool none --minimal"

## count_regions configuration
# Should regions be counted by individual contigs rather than genome?
contig: False
# Should hybrid regions be counted once as 'hybrid' rather than counted for each BGC class?
hybrid: False

## BiG-SCAPE configuration
# BiG-SCAPE is likewise not conda installable
bigscape_command: "bigscape.py"
bigscape_conda: "bigscape"
bigscape_flags:   # in addition to -i, -o, and pfam_dir
  "--mix --no_classify --include_singletons --clans-off --cutoffs 0.3 0.4 0.5 0.6 0.7"